# Generated by Django 5.1.4 on 2024-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Hourly Rate'),
        ),
        migrations.AddField(
            model_name='computer',
            name='reserved_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reservation Start Time'),
        ),
        migrations.AddField(
            model_name='computer',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reservation End Time'),
        ),
    ]
